title: Dongchan Lee
description: Applied scientist working in robotics, optimization, and machine learning.

theme: minima

collections:
  notes:
    output: true
    permalink: /notes/:name/

defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: page

# Google Analytics
google_analytics: G-PTJ77LWFND
